import React, {useState} from 'react'
import Head from 'next/head';
import theme from '../theme'
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer} from 'react-toastify';
import TopBar from '../container/TopBar';
import { Box, ThemeProvider, CssBaseline, Drawer, IconButton, Toolbar, Typography, Paper, InputBase, Avatar} from '@mui/material';
import { CgMenuLeft,CgMenuRightAlt } from "react-icons/cg";
import SideBar from '../container/SideBar'
import { Search } from '@mui/icons-material';

const drawerWidthOpen = 240;
const paddingIconButton = 10;
const marginIconButton = 14;
const iconFontSize = 10;
const drawerWidthClose = (paddingIconButton + marginIconButton) * 2 + iconFontSize;

export default function Layout({children}) {
  const [open, setOpen] = useState(false);
  function toogleOpen() {
    setOpen(!open);
  }

  return (
    <>
      <Head>
        <title>Welcome to Fortunetech Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />
      <ThemeProvider theme={theme}>
        <Box display='flex'>
          <Drawer variant="permanent" open={open}
            sx={{
              width: open
                ? { xs: "0px", sm: drawerWidthClose }
                : { xs: drawerWidthClose, sm: drawerWidthOpen },
              transition: theme.transitions.create("width", {
                easing: theme.transitions.easing.sharp,
                duration: open
                  ? theme.transitions.duration.leavingScreen
                  : theme.transitions.duration.enteringScreen
              }),
              "& .MuiDrawer-paper": {
                justifyContent: "space-between",
                overflowX: "hidden",
                width: open
                  ? { xs: "0px", sm: drawerWidthClose }
                  : { xs: drawerWidthClose, sm: drawerWidthOpen },
                backgroundColor: 'primary.dark',
                color: 'primary.main',
                transition: theme.transitions.create("width", {
                  easing: theme.transitions.easing.sharp,
                  duration: open
                    ? theme.transitions.duration.leavingScreen
                    : theme.transitions.duration.enteringScreen
                })
              }
            }}
          >
            <Box>
              <Toolbar>
                {open ? <Typography variant="h4" sx={{ flexGrow: 1 }}> F </Typography> : <Typography variant="h6" sx={{ flexGrow: 1 }}> Fortunetech </Typography>}
              </Toolbar>
              <SideBar/>
            </Box>
          </Drawer>
          <Box component="div" flex='1'>
            <Box bgcolor={'primary.dark'} color={'primary.main'}>
              <Toolbar sx={{justifyContent: 'space-between'}}>
                <IconButton size='large' onClick={toogleOpen} color="primary" sx={{marginRight: '15px'}}>
                  {open ? <CgMenuLeft/> : <CgMenuRightAlt/>}
                </IconButton>
                <Box component='div' >
                  <Paper
                    component="form"
                    sx={{ display: 'flex', alignItems: 'center', width: {sm: 200, md: 300, lg: 800}, backgroundColor: '#4a4a4a', border: '1px solid #4e4e4e'}}
                  >
                    <InputBase
                      sx={{ ml: 1, flex: 1, color: 'primary.main' }}
                      placeholder="Search here..."
                      inputProps={{ 'aria-label': 'Search here...' }}
                    />
                    <IconButton type="submit" sx={{ p: '10px' }} aria-label="search">
                      <Search sx={{ color: '#918f8f'}}/>
                    </IconButton>
                  </Paper>
                </Box>
                <TopBar />
              </Toolbar>
            </Box>
            {children}
          </Box>
        </Box>
        
      <ToastContainer position="bottom-right" autoClose={3000} hideProgressBar={false} newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss={false} draggable pauseOnHover={false} />
      </ThemeProvider>
    </>
  )
}
